name: Deploy to Render

on:
  push:
    branches:
      - main  # Trigger khi push lên main branch
  workflow_dispatch:  # Cho phép trigger thủ công

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run tests (optional)
        run: |
          echo "✅ Tests would run here"
          # python -m pytest tests/
      
      - name: Trigger Render Deploy
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
        run: |
          curl -X POST $RENDER_DEPLOY_HOOK
      
      - name: Deployment notification
        run: |
          echo "🚀 Deployment triggered successfully!"
          echo "Check Render dashboard for deployment status"